Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var
// Seção de Declarações das variáveis 
x,y,z: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

x <- 1
y <- 2
z <- y-x
escreval(z)
x <- 5
y <- x
escreval(x,y,z)

Fimalgoritmo