Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var
// Seção de Declarações das variáveis 
a: inteiro
b: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

a <- 10
b <- 20
escreval(b)
b <- 5
escreval(a,b)

Fimalgoritmo